// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName
console.log("Hello from index.js");
import { application } from "./application"

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import VideoController from "./video_controller.js"
application.register("video", VideoController)
